---
# Ansible playbook for an Apache Solr server.
#
# @author Jeff Geerling (2014).

- hosts: jenkins
  sudo: yes
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - mws.mws-repo
    - mws.build-prereqs
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.java
    - geerlingguy.jenkins
